/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GameRouteImport } from './routes/game'
import { Route as CaseyRouteImport } from './routes/casey'
import { Route as BuildRouteImport } from './routes/build'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseyIndexRouteImport } from './routes/casey.index'
import { Route as CaseyAdminRouteImport } from './routes/casey.admin'
import { Route as ApiVisibilityRouteImport } from './routes/api/visibility'
import { Route as ApiTodayRouteImport } from './routes/api/today'
import { Route as ApiStandingsRouteImport } from './routes/api/standings'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiMatchScoreRouteImport } from './routes/api/match-score'
import { Route as ApiLiveTodayRouteImport } from './routes/api/live-today'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiBracketRouteImport } from './routes/api/bracket'
import { Route as ApiBootstrapRouteImport } from './routes/api/bootstrap'
import { Route as CaseyMatchNumberRouteImport } from './routes/casey_.match.$number'
import { Route as ApiStandingsAllRouteImport } from './routes/api/standings.all'
import { Route as ApiAdminUpdateRouteImport } from './routes/api/admin/update'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminEspnHealthRouteImport } from './routes/api/admin/espn-health'
import { Route as ApiAdminBootstrapRouteImport } from './routes/api/admin/bootstrap'
import { Route as ApiAdminAttentionRouteImport } from './routes/api/admin/attention'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseyRoute = CaseyRouteImport.update({
  id: '/casey',
  path: '/casey',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseyIndexRoute = CaseyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseyRoute,
} as any)
const CaseyAdminRoute = CaseyAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CaseyRoute,
} as any)
const ApiVisibilityRoute = ApiVisibilityRouteImport.update({
  id: '/api/visibility',
  path: '/api/visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodayRoute = ApiTodayRouteImport.update({
  id: '/api/today',
  path: '/api/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStandingsRoute = ApiStandingsRouteImport.update({
  id: '/api/standings',
  path: '/api/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchScoreRoute = ApiMatchScoreRouteImport.update({
  id: '/api/match-score',
  path: '/api/match-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveTodayRoute = ApiLiveTodayRouteImport.update({
  id: '/api/live-today',
  path: '/api/live-today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBracketRoute = ApiBracketRouteImport.update({
  id: '/api/bracket',
  path: '/api/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapRoute = ApiBootstrapRouteImport.update({
  id: '/api/bootstrap',
  path: '/api/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseyMatchNumberRoute = CaseyMatchNumberRouteImport.update({
  id: '/casey_/match/$number',
  path: '/casey/match/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStandingsAllRoute = ApiStandingsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ApiStandingsRoute,
} as any)
const ApiAdminUpdateRoute = ApiAdminUpdateRouteImport.update({
  id: '/api/admin/update',
  path: '/api/admin/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEspnHealthRoute = ApiAdminEspnHealthRouteImport.update({
  id: '/api/admin/espn-health',
  path: '/api/admin/espn-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBootstrapRoute = ApiAdminBootstrapRouteImport.update({
  id: '/api/admin/bootstrap',
  path: '/api/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAttentionRoute = ApiAdminAttentionRouteImport.update({
  id: '/api/admin/attention',
  path: '/api/admin/attention',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/build': typeof BuildRoute
  '/casey': typeof CaseyRouteWithChildren
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/venue': typeof VenueRoute
  '/venues': typeof VenuesRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/bracket': typeof ApiBracketRoute
  '/api/live': typeof ApiLiveRoute
  '/api/live-today': typeof ApiLiveTodayRoute
  '/api/match-score': typeof ApiMatchScoreRoute
  '/api/og': typeof ApiOgRoute
  '/api/standings': typeof ApiStandingsRouteWithChildren
  '/api/today': typeof ApiTodayRoute
  '/api/visibility': typeof ApiVisibilityRoute
  '/casey/admin': typeof CaseyAdminRoute
  '/casey/': typeof CaseyIndexRoute
  '/api/admin/attention': typeof ApiAdminAttentionRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/espn-health': typeof ApiAdminEspnHealthRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/standings/all': typeof ApiStandingsAllRoute
  '/casey/match/$number': typeof CaseyMatchNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/build': typeof BuildRoute
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/venue': typeof VenueRoute
  '/venues': typeof VenuesRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/bracket': typeof ApiBracketRoute
  '/api/live': typeof ApiLiveRoute
  '/api/live-today': typeof ApiLiveTodayRoute
  '/api/match-score': typeof ApiMatchScoreRoute
  '/api/og': typeof ApiOgRoute
  '/api/standings': typeof ApiStandingsRouteWithChildren
  '/api/today': typeof ApiTodayRoute
  '/api/visibility': typeof ApiVisibilityRoute
  '/casey/admin': typeof CaseyAdminRoute
  '/casey': typeof CaseyIndexRoute
  '/api/admin/attention': typeof ApiAdminAttentionRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/espn-health': typeof ApiAdminEspnHealthRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/standings/all': typeof ApiStandingsAllRoute
  '/casey/match/$number': typeof CaseyMatchNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/build': typeof BuildRoute
  '/casey': typeof CaseyRouteWithChildren
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/venue': typeof VenueRoute
  '/venues': typeof VenuesRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/bracket': typeof ApiBracketRoute
  '/api/live': typeof ApiLiveRoute
  '/api/live-today': typeof ApiLiveTodayRoute
  '/api/match-score': typeof ApiMatchScoreRoute
  '/api/og': typeof ApiOgRoute
  '/api/standings': typeof ApiStandingsRouteWithChildren
  '/api/today': typeof ApiTodayRoute
  '/api/visibility': typeof ApiVisibilityRoute
  '/casey/admin': typeof CaseyAdminRoute
  '/casey/': typeof CaseyIndexRoute
  '/api/admin/attention': typeof ApiAdminAttentionRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/espn-health': typeof ApiAdminEspnHealthRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/standings/all': typeof ApiStandingsAllRoute
  '/casey_/match/$number': typeof CaseyMatchNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/build'
    | '/casey'
    | '/game'
    | '/games'
    | '/guide'
    | '/venue'
    | '/venues'
    | '/api/bootstrap'
    | '/api/bracket'
    | '/api/live'
    | '/api/live-today'
    | '/api/match-score'
    | '/api/og'
    | '/api/standings'
    | '/api/today'
    | '/api/visibility'
    | '/casey/admin'
    | '/casey/'
    | '/api/admin/attention'
    | '/api/admin/bootstrap'
    | '/api/admin/espn-health'
    | '/api/admin/login'
    | '/api/admin/update'
    | '/api/standings/all'
    | '/casey/match/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/build'
    | '/game'
    | '/games'
    | '/guide'
    | '/venue'
    | '/venues'
    | '/api/bootstrap'
    | '/api/bracket'
    | '/api/live'
    | '/api/live-today'
    | '/api/match-score'
    | '/api/og'
    | '/api/standings'
    | '/api/today'
    | '/api/visibility'
    | '/casey/admin'
    | '/casey'
    | '/api/admin/attention'
    | '/api/admin/bootstrap'
    | '/api/admin/espn-health'
    | '/api/admin/login'
    | '/api/admin/update'
    | '/api/standings/all'
    | '/casey/match/$number'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/build'
    | '/casey'
    | '/game'
    | '/games'
    | '/guide'
    | '/venue'
    | '/venues'
    | '/api/bootstrap'
    | '/api/bracket'
    | '/api/live'
    | '/api/live-today'
    | '/api/match-score'
    | '/api/og'
    | '/api/standings'
    | '/api/today'
    | '/api/visibility'
    | '/casey/admin'
    | '/casey/'
    | '/api/admin/attention'
    | '/api/admin/bootstrap'
    | '/api/admin/espn-health'
    | '/api/admin/login'
    | '/api/admin/update'
    | '/api/standings/all'
    | '/casey_/match/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BuildRoute: typeof BuildRoute
  CaseyRoute: typeof CaseyRouteWithChildren
  GameRoute: typeof GameRoute
  GamesRoute: typeof GamesRoute
  GuideRoute: typeof GuideRoute
  VenueRoute: typeof VenueRoute
  VenuesRoute: typeof VenuesRoute
  ApiBootstrapRoute: typeof ApiBootstrapRoute
  ApiBracketRoute: typeof ApiBracketRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiLiveTodayRoute: typeof ApiLiveTodayRoute
  ApiMatchScoreRoute: typeof ApiMatchScoreRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiStandingsRoute: typeof ApiStandingsRouteWithChildren
  ApiTodayRoute: typeof ApiTodayRoute
  ApiVisibilityRoute: typeof ApiVisibilityRoute
  ApiAdminAttentionRoute: typeof ApiAdminAttentionRoute
  ApiAdminBootstrapRoute: typeof ApiAdminBootstrapRoute
  ApiAdminEspnHealthRoute: typeof ApiAdminEspnHealthRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminUpdateRoute: typeof ApiAdminUpdateRoute
  CaseyMatchNumberRoute: typeof CaseyMatchNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casey': {
      id: '/casey'
      path: '/casey'
      fullPath: '/casey'
      preLoaderRoute: typeof CaseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casey/': {
      id: '/casey/'
      path: '/'
      fullPath: '/casey/'
      preLoaderRoute: typeof CaseyIndexRouteImport
      parentRoute: typeof CaseyRoute
    }
    '/casey/admin': {
      id: '/casey/admin'
      path: '/admin'
      fullPath: '/casey/admin'
      preLoaderRoute: typeof CaseyAdminRouteImport
      parentRoute: typeof CaseyRoute
    }
    '/api/visibility': {
      id: '/api/visibility'
      path: '/api/visibility'
      fullPath: '/api/visibility'
      preLoaderRoute: typeof ApiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/today': {
      id: '/api/today'
      path: '/api/today'
      fullPath: '/api/today'
      preLoaderRoute: typeof ApiTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/standings': {
      id: '/api/standings'
      path: '/api/standings'
      fullPath: '/api/standings'
      preLoaderRoute: typeof ApiStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match-score': {
      id: '/api/match-score'
      path: '/api/match-score'
      fullPath: '/api/match-score'
      preLoaderRoute: typeof ApiMatchScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-today': {
      id: '/api/live-today'
      path: '/api/live-today'
      fullPath: '/api/live-today'
      preLoaderRoute: typeof ApiLiveTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bracket': {
      id: '/api/bracket'
      path: '/api/bracket'
      fullPath: '/api/bracket'
      preLoaderRoute: typeof ApiBracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap': {
      id: '/api/bootstrap'
      path: '/api/bootstrap'
      fullPath: '/api/bootstrap'
      preLoaderRoute: typeof ApiBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casey_/match/$number': {
      id: '/casey_/match/$number'
      path: '/casey/match/$number'
      fullPath: '/casey/match/$number'
      preLoaderRoute: typeof CaseyMatchNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/standings/all': {
      id: '/api/standings/all'
      path: '/all'
      fullPath: '/api/standings/all'
      preLoaderRoute: typeof ApiStandingsAllRouteImport
      parentRoute: typeof ApiStandingsRoute
    }
    '/api/admin/update': {
      id: '/api/admin/update'
      path: '/api/admin/update'
      fullPath: '/api/admin/update'
      preLoaderRoute: typeof ApiAdminUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/espn-health': {
      id: '/api/admin/espn-health'
      path: '/api/admin/espn-health'
      fullPath: '/api/admin/espn-health'
      preLoaderRoute: typeof ApiAdminEspnHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bootstrap': {
      id: '/api/admin/bootstrap'
      path: '/api/admin/bootstrap'
      fullPath: '/api/admin/bootstrap'
      preLoaderRoute: typeof ApiAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/attention': {
      id: '/api/admin/attention'
      path: '/api/admin/attention'
      fullPath: '/api/admin/attention'
      preLoaderRoute: typeof ApiAdminAttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseyRouteChildren {
  CaseyAdminRoute: typeof CaseyAdminRoute
  CaseyIndexRoute: typeof CaseyIndexRoute
}

const CaseyRouteChildren: CaseyRouteChildren = {
  CaseyAdminRoute: CaseyAdminRoute,
  CaseyIndexRoute: CaseyIndexRoute,
}

const CaseyRouteWithChildren = CaseyRoute._addFileChildren(CaseyRouteChildren)

interface ApiStandingsRouteChildren {
  ApiStandingsAllRoute: typeof ApiStandingsAllRoute
}

const ApiStandingsRouteChildren: ApiStandingsRouteChildren = {
  ApiStandingsAllRoute: ApiStandingsAllRoute,
}

const ApiStandingsRouteWithChildren = ApiStandingsRoute._addFileChildren(
  ApiStandingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BuildRoute: BuildRoute,
  CaseyRoute: CaseyRouteWithChildren,
  GameRoute: GameRoute,
  GamesRoute: GamesRoute,
  GuideRoute: GuideRoute,
  VenueRoute: VenueRoute,
  VenuesRoute: VenuesRoute,
  ApiBootstrapRoute: ApiBootstrapRoute,
  ApiBracketRoute: ApiBracketRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiLiveTodayRoute: ApiLiveTodayRoute,
  ApiMatchScoreRoute: ApiMatchScoreRoute,
  ApiOgRoute: ApiOgRoute,
  ApiStandingsRoute: ApiStandingsRouteWithChildren,
  ApiTodayRoute: ApiTodayRoute,
  ApiVisibilityRoute: ApiVisibilityRoute,
  ApiAdminAttentionRoute: ApiAdminAttentionRoute,
  ApiAdminBootstrapRoute: ApiAdminBootstrapRoute,
  ApiAdminEspnHealthRoute: ApiAdminEspnHealthRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminUpdateRoute: ApiAdminUpdateRoute,
  CaseyMatchNumberRoute: CaseyMatchNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
