/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CaseyRouteImport } from './routes/casey'
import { Route as IndexRouteImport } from './routes/index'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseyRoute = CaseyRouteImport.update({
  id: '/casey',
  path: '/casey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casey': typeof CaseyRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/venue': typeof VenueRoute
  '/venues': typeof VenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casey': typeof CaseyRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/venue': typeof VenueRoute
  '/venues': typeof VenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casey': typeof CaseyRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/venue': typeof VenueRoute
  '/venues': typeof VenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/casey' | '/games' | '/guide' | '/venue' | '/venues'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/casey' | '/games' | '/guide' | '/venue' | '/venues'
  id: '__root__' | '/' | '/casey' | '/games' | '/guide' | '/venue' | '/venues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseyRoute: typeof CaseyRoute
  GamesRoute: typeof GamesRoute
  GuideRoute: typeof GuideRoute
  VenueRoute: typeof VenueRoute
  VenuesRoute: typeof VenuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casey': {
      id: '/casey'
      path: '/casey'
      fullPath: '/casey'
      preLoaderRoute: typeof CaseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseyRoute: CaseyRoute,
  GamesRoute: GamesRoute,
  GuideRoute: GuideRoute,
  VenueRoute: VenueRoute,
  VenuesRoute: VenuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
