/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeekendRouteImport } from './routes/weekend'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as VenuePlanRouteImport } from './routes/venue-plan'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RankRouteImport } from './routes/rank'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GameRouteImport } from './routes/game'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as ApiVenuesRouteImport } from './routes/api/venues'
import { Route as ApiVenueStatsRouteImport } from './routes/api/venue-stats'
import { Route as ApiTipsRouteImport } from './routes/api/tips'
import { Route as ApiTipVotesRouteImport } from './routes/api/tip-votes'
import { Route as ApiTeamsRouteImport } from './routes/api/teams'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ApiReviewVotesRouteImport } from './routes/api/review-votes'
import { Route as ApiRankingsRouteImport } from './routes/api/rankings'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiMatchScoreRouteImport } from './routes/api/match-score'
import { Route as ApiGamesRouteImport } from './routes/api/games'
import { Route as ApiFollowRouteImport } from './routes/api/follow'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiExpertNotesRouteImport } from './routes/api/expert-notes'
import { Route as ApiConferencesRouteImport } from './routes/api/conferences'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as ApiUUsernameRouteImport } from './routes/api/u/$username'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthConfigRouteImport } from './routes/api/auth/config'

const WeekendRoute = WeekendRouteImport.update({
  id: '/weekend',
  path: '/weekend',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuePlanRoute = VenuePlanRouteImport.update({
  id: '/venue-plan',
  path: '/venue-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVenuesRoute = ApiVenuesRouteImport.update({
  id: '/api/venues',
  path: '/api/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVenueStatsRoute = ApiVenueStatsRouteImport.update({
  id: '/api/venue-stats',
  path: '/api/venue-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipsRoute = ApiTipsRouteImport.update({
  id: '/api/tips',
  path: '/api/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTipVotesRoute = ApiTipVotesRouteImport.update({
  id: '/api/tip-votes',
  path: '/api/tip-votes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewVotesRoute = ApiReviewVotesRouteImport.update({
  id: '/api/review-votes',
  path: '/api/review-votes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsRoute = ApiRankingsRouteImport.update({
  id: '/api/rankings',
  path: '/api/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchScoreRoute = ApiMatchScoreRouteImport.update({
  id: '/api/match-score',
  path: '/api/match-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoute = ApiGamesRouteImport.update({
  id: '/api/games',
  path: '/api/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowRoute = ApiFollowRouteImport.update({
  id: '/api/follow',
  path: '/api/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpertNotesRoute = ApiExpertNotesRouteImport.update({
  id: '/api/expert-notes',
  path: '/api/expert-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConferencesRoute = ApiConferencesRouteImport.update({
  id: '/api/conferences',
  path: '/api/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUUsernameRoute = ApiUUsernameRouteImport.update({
  id: '/api/u/$username',
  path: '/api/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfigRoute = ApiAuthConfigRouteImport.update({
  id: '/api/auth/config',
  path: '/api/auth/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/conferences': typeof ConferencesRoute
  '/feed': typeof FeedRoute
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/profile': typeof ProfileRoute
  '/rank': typeof RankRoute
  '/rankings': typeof RankingsRoute
  '/team': typeof TeamRoute
  '/teams': typeof TeamsRoute
  '/venue': typeof VenueRoute
  '/venue-plan': typeof VenuePlanRoute
  '/venues': typeof VenuesRoute
  '/weekend': typeof WeekendRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/conferences': typeof ApiConferencesRoute
  '/api/expert-notes': typeof ApiExpertNotesRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/follow': typeof ApiFollowRoute
  '/api/games': typeof ApiGamesRoute
  '/api/match-score': typeof ApiMatchScoreRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/review-votes': typeof ApiReviewVotesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/tip-votes': typeof ApiTipVotesRoute
  '/api/tips': typeof ApiTipsRoute
  '/api/venue-stats': typeof ApiVenueStatsRoute
  '/api/venues': typeof ApiVenuesRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/u/$username': typeof ApiUUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/conferences': typeof ConferencesRoute
  '/feed': typeof FeedRoute
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/profile': typeof ProfileRoute
  '/rank': typeof RankRoute
  '/rankings': typeof RankingsRoute
  '/team': typeof TeamRoute
  '/teams': typeof TeamsRoute
  '/venue': typeof VenueRoute
  '/venue-plan': typeof VenuePlanRoute
  '/venues': typeof VenuesRoute
  '/weekend': typeof WeekendRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/conferences': typeof ApiConferencesRoute
  '/api/expert-notes': typeof ApiExpertNotesRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/follow': typeof ApiFollowRoute
  '/api/games': typeof ApiGamesRoute
  '/api/match-score': typeof ApiMatchScoreRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/review-votes': typeof ApiReviewVotesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/tip-votes': typeof ApiTipVotesRoute
  '/api/tips': typeof ApiTipsRoute
  '/api/venue-stats': typeof ApiVenueStatsRoute
  '/api/venues': typeof ApiVenuesRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/u/$username': typeof ApiUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/conferences': typeof ConferencesRoute
  '/feed': typeof FeedRoute
  '/game': typeof GameRoute
  '/games': typeof GamesRoute
  '/profile': typeof ProfileRoute
  '/rank': typeof RankRoute
  '/rankings': typeof RankingsRoute
  '/team': typeof TeamRoute
  '/teams': typeof TeamsRoute
  '/venue': typeof VenueRoute
  '/venue-plan': typeof VenuePlanRoute
  '/venues': typeof VenuesRoute
  '/weekend': typeof WeekendRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/conferences': typeof ApiConferencesRoute
  '/api/expert-notes': typeof ApiExpertNotesRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/follow': typeof ApiFollowRoute
  '/api/games': typeof ApiGamesRoute
  '/api/match-score': typeof ApiMatchScoreRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/review-votes': typeof ApiReviewVotesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/tip-votes': typeof ApiTipVotesRoute
  '/api/tips': typeof ApiTipsRoute
  '/api/venue-stats': typeof ApiVenueStatsRoute
  '/api/venues': typeof ApiVenuesRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/u/$username': typeof ApiUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/conferences'
    | '/feed'
    | '/game'
    | '/games'
    | '/profile'
    | '/rank'
    | '/rankings'
    | '/team'
    | '/teams'
    | '/venue'
    | '/venue-plan'
    | '/venues'
    | '/weekend'
    | '/api/assistant'
    | '/api/conferences'
    | '/api/expert-notes'
    | '/api/feed'
    | '/api/follow'
    | '/api/games'
    | '/api/match-score'
    | '/api/profile'
    | '/api/rankings'
    | '/api/review-votes'
    | '/api/reviews'
    | '/api/search'
    | '/api/teams'
    | '/api/tip-votes'
    | '/api/tips'
    | '/api/venue-stats'
    | '/api/venues'
    | '/u/$username'
    | '/api/auth/config'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/conferences'
    | '/feed'
    | '/game'
    | '/games'
    | '/profile'
    | '/rank'
    | '/rankings'
    | '/team'
    | '/teams'
    | '/venue'
    | '/venue-plan'
    | '/venues'
    | '/weekend'
    | '/api/assistant'
    | '/api/conferences'
    | '/api/expert-notes'
    | '/api/feed'
    | '/api/follow'
    | '/api/games'
    | '/api/match-score'
    | '/api/profile'
    | '/api/rankings'
    | '/api/review-votes'
    | '/api/reviews'
    | '/api/search'
    | '/api/teams'
    | '/api/tip-votes'
    | '/api/tips'
    | '/api/venue-stats'
    | '/api/venues'
    | '/u/$username'
    | '/api/auth/config'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/u/$username'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/conferences'
    | '/feed'
    | '/game'
    | '/games'
    | '/profile'
    | '/rank'
    | '/rankings'
    | '/team'
    | '/teams'
    | '/venue'
    | '/venue-plan'
    | '/venues'
    | '/weekend'
    | '/api/assistant'
    | '/api/conferences'
    | '/api/expert-notes'
    | '/api/feed'
    | '/api/follow'
    | '/api/games'
    | '/api/match-score'
    | '/api/profile'
    | '/api/rankings'
    | '/api/review-votes'
    | '/api/reviews'
    | '/api/search'
    | '/api/teams'
    | '/api/tip-votes'
    | '/api/tips'
    | '/api/venue-stats'
    | '/api/venues'
    | '/u/$username'
    | '/api/auth/config'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConferencesRoute: typeof ConferencesRoute
  FeedRoute: typeof FeedRoute
  GameRoute: typeof GameRoute
  GamesRoute: typeof GamesRoute
  ProfileRoute: typeof ProfileRoute
  RankRoute: typeof RankRoute
  RankingsRoute: typeof RankingsRoute
  TeamRoute: typeof TeamRoute
  TeamsRoute: typeof TeamsRoute
  VenueRoute: typeof VenueRoute
  VenuePlanRoute: typeof VenuePlanRoute
  VenuesRoute: typeof VenuesRoute
  WeekendRoute: typeof WeekendRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiConferencesRoute: typeof ApiConferencesRoute
  ApiExpertNotesRoute: typeof ApiExpertNotesRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiFollowRoute: typeof ApiFollowRoute
  ApiGamesRoute: typeof ApiGamesRoute
  ApiMatchScoreRoute: typeof ApiMatchScoreRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiRankingsRoute: typeof ApiRankingsRoute
  ApiReviewVotesRoute: typeof ApiReviewVotesRoute
  ApiReviewsRoute: typeof ApiReviewsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTeamsRoute: typeof ApiTeamsRoute
  ApiTipVotesRoute: typeof ApiTipVotesRoute
  ApiTipsRoute: typeof ApiTipsRoute
  ApiVenueStatsRoute: typeof ApiVenueStatsRoute
  ApiVenuesRoute: typeof ApiVenuesRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAuthConfigRoute: typeof ApiAuthConfigRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiUUsernameRoute: typeof ApiUUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekend': {
      id: '/weekend'
      path: '/weekend'
      fullPath: '/weekend'
      preLoaderRoute: typeof WeekendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue-plan': {
      id: '/venue-plan'
      path: '/venue-plan'
      fullPath: '/venue-plan'
      preLoaderRoute: typeof VenuePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/venues': {
      id: '/api/venues'
      path: '/api/venues'
      fullPath: '/api/venues'
      preLoaderRoute: typeof ApiVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/venue-stats': {
      id: '/api/venue-stats'
      path: '/api/venue-stats'
      fullPath: '/api/venue-stats'
      preLoaderRoute: typeof ApiVenueStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tips': {
      id: '/api/tips'
      path: '/api/tips'
      fullPath: '/api/tips'
      preLoaderRoute: typeof ApiTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tip-votes': {
      id: '/api/tip-votes'
      path: '/api/tip-votes'
      fullPath: '/api/tip-votes'
      preLoaderRoute: typeof ApiTipVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-votes': {
      id: '/api/review-votes'
      path: '/api/review-votes'
      fullPath: '/api/review-votes'
      preLoaderRoute: typeof ApiReviewVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings': {
      id: '/api/rankings'
      path: '/api/rankings'
      fullPath: '/api/rankings'
      preLoaderRoute: typeof ApiRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match-score': {
      id: '/api/match-score'
      path: '/api/match-score'
      fullPath: '/api/match-score'
      preLoaderRoute: typeof ApiMatchScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games': {
      id: '/api/games'
      path: '/api/games'
      fullPath: '/api/games'
      preLoaderRoute: typeof ApiGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/follow': {
      id: '/api/follow'
      path: '/api/follow'
      fullPath: '/api/follow'
      preLoaderRoute: typeof ApiFollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expert-notes': {
      id: '/api/expert-notes'
      path: '/api/expert-notes'
      fullPath: '/api/expert-notes'
      preLoaderRoute: typeof ApiExpertNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conferences': {
      id: '/api/conferences'
      path: '/api/conferences'
      fullPath: '/api/conferences'
      preLoaderRoute: typeof ApiConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/u/$username': {
      id: '/api/u/$username'
      path: '/api/u/$username'
      fullPath: '/api/u/$username'
      preLoaderRoute: typeof ApiUUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/config': {
      id: '/api/auth/config'
      path: '/api/auth/config'
      fullPath: '/api/auth/config'
      preLoaderRoute: typeof ApiAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConferencesRoute: ConferencesRoute,
  FeedRoute: FeedRoute,
  GameRoute: GameRoute,
  GamesRoute: GamesRoute,
  ProfileRoute: ProfileRoute,
  RankRoute: RankRoute,
  RankingsRoute: RankingsRoute,
  TeamRoute: TeamRoute,
  TeamsRoute: TeamsRoute,
  VenueRoute: VenueRoute,
  VenuePlanRoute: VenuePlanRoute,
  VenuesRoute: VenuesRoute,
  WeekendRoute: WeekendRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiConferencesRoute: ApiConferencesRoute,
  ApiExpertNotesRoute: ApiExpertNotesRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiFollowRoute: ApiFollowRoute,
  ApiGamesRoute: ApiGamesRoute,
  ApiMatchScoreRoute: ApiMatchScoreRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiRankingsRoute: ApiRankingsRoute,
  ApiReviewVotesRoute: ApiReviewVotesRoute,
  ApiReviewsRoute: ApiReviewsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTeamsRoute: ApiTeamsRoute,
  ApiTipVotesRoute: ApiTipVotesRoute,
  ApiTipsRoute: ApiTipsRoute,
  ApiVenueStatsRoute: ApiVenueStatsRoute,
  ApiVenuesRoute: ApiVenuesRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAuthConfigRoute: ApiAuthConfigRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiUUsernameRoute: ApiUUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
